### ISSUE TITLE
[BUG] flutter_lottie 0.2.0 doesn't support null safety

### ISSUE THREAD

**Issue by chiggosVikash** [igniti0n/flutter_algorithms_visualization#3]
Issue Description:
 I am currently working on a project that involves using the path_finding package along with the flutter_lottie package for animations. However, I've run into an issue related to null safety compatibility with the flutter_lottie package version 0.2.0. Unfortunately, this is causing problems when trying to resolve dependencies during my Flutter project build.

The problem arises from the fact that the flutter_lottie package is not null safe in version 0.2.0, and there seems to be no version of the package that fits the requirement of >0.2.0 <0.3.0. As a result, I'm unable to include the flutter_lottie package in my project while maintaining compatibility with null safety.

Expected Behavior:
 I expected that I would be able to include the flutter_lottie package with version ^0.2.0 in my project and successfully resolve 
 dependencies during the build process.

Current Behavior:
Instead, I'm encountering an error message that states that flutter_lottie ^0.2.0 is forbidden and that version solving failed due to the dependency conflict.

Steps to Reproduce:
Run flutter pub get or try to build the project.

Screenshots (if applicable):
![image](https://github.com/igniti0n/flutter_algorithms_visualization/assets/98211278/1eb17d50-4a8a-46dd-98cb-1123534008ff)

**Comment by igniti0n** [comment]
These packages are old and seem to not be very useful:

https://pub.dev/packages/flutter_lottie (updated 4y ago)
https://pub.dev/packages/path_finding/versions (updated 7y ago)

If you are using these packages - why do you need to use these ones? They are not null safe + outdated.

Here is a package for pathfinding that is null-safe and updated 10 months ago: https://pub.dev/packages/pathfinding
Here is a Lottie package: https://pub.dev/packages/lottie

I have not used any package like that for my `flutter_algorithms_visualization` project, so I can't vouch for it. But, I would suggest not to use these outdated packages. Instead, use the ones that are maintained, or even better - implement them yourself (it's fun 😄)

Hope this fixes your issue - if you have any other questions, feel free to ask.
